### ISSUE TITLE
Yaml to Rails (action_dispatch, action_view, …) options

### ISSUE THREAD

**Issue by sunny** [mislav/choices#4]
I'd like to write yaml settings like this :

```
development:
  action_mailer:
    perform_deliveries: true
    raise_delivery_errors: false
```

That would translate in Rails's config block to :

```
config.action_mailer.perform_deliveries = true
config.action_mailer.raise_delivery_errors = true
```

Could that be possible ?
